In [1]:
# 测试 expert.py 中的 Expert
# 查看保存的 expert 数据
# liyi, 2019/6/27

from expert import Expert

expert_dir = './expert_data/HalfCheetah-v2'
data = Expert(expert_dir)
print(data.value())

/home/liyi/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


Expert dataset initialized!
length  1000000
states  torch.Size([1000, 1000, 17])
episode  59001 tensor([-0.0086])
episode  59002 tensor([-0.0022])
episode  59003 tensor([0.0034])
episode  59004 tensor([0.0002])
episode  59005 tensor([-0.0030])
episode  59006 tensor([-0.0097])
episode  59007 tensor([-0.0016])
episode  59008 tensor([0.0049])
episode  59009 tensor([0.0048])
episode  59010 tensor([0.0010])
episode  59011 tensor([-0.0085])
episode  59012 tensor([-0.0069])
episode  59013 tensor([0.0091])
episode  59014 tensor([0.0088])
episode  59015 tensor([-0.0028])
episode  59016 tensor([-0.0041])
episode  59017 tensor([0.0020])
episode  59018 tensor([0.0033])
episode  59019 tensor([0.0129])
episode  59020 tensor([0.0129])
episode  59021 tensor([0.0024])
episode  59022 tensor([0.0102])
episode  59023 tensor([0.0073])
episode  59024 tensor([0.0008])
episode  59025 tensor([-0.0027])
episode  59026 tensor([-0.0006])
episode  59027 tensor([0.0051])
episode  59028 tensor([0.0022])
episode  590

episode  59507 tensor([0.0105])
episode  59508 tensor([0.0222])
episode  59509 tensor([0.0221])
episode  59510 tensor([0.0163])
episode  59511 tensor([0.0099])
episode  59512 tensor([0.0053])
episode  59513 tensor([0.0194])
episode  59514 tensor([0.0327])
episode  59515 tensor([0.0228])
episode  59516 tensor([0.0082])
episode  59517 tensor([0.0187])
episode  59518 tensor([0.0240])
episode  59519 tensor([0.0178])
episode  59520 tensor([0.0125])
episode  59521 tensor([0.0129])
episode  59522 tensor([0.0167])
episode  59523 tensor([0.0215])
episode  59524 tensor([0.0286])
episode  59525 tensor([0.0171])
episode  59526 tensor([0.0053])
episode  59527 tensor([0.0123])
episode  59528 tensor([0.0174])
episode  59529 tensor([0.0179])
episode  59530 tensor([0.0126])
episode  59531 tensor([0.0067])
episode  59532 tensor([0.0021])
episode  59533 tensor([0.0148])
episode  59534 tensor([0.0288])
episode  59535 tensor([0.0207])
episode  59536 tensor([0.0087])
episode  59537 tensor([0.0207])
episode 

In [4]:
data.__getitem__(500000)

(tensor([ 1.8662, -0.8942, -0.1869, -0.3047,  0.0350,  0.0314,  0.2415, -0.0224,
         -0.0376,  0.0464, -0.1102, -0.0132,  0.0186, -0.0056,  0.0031,  0.0122,
          0.0115]),
 tensor([-0.2128, -0.2207,  0.0180, -0.8264, -0.1154, -1.3213]),
 tensor([-0.0048]),
 tensor(0.))