In [8]:
# 测试 expert.py 中的 Expert
# 查看保存的 expert 数据
# liyi, 2019/6/27

from expert import Expert

env_name = ['HalfCheetah-v2', 'Hopper-v2', 'Walker2d-v2']
expert_dir = './expert_data/ppo_1/'+env_name[0]
data = Expert(expert_dir)
print(data.value(num_episodes=50))

Expert dataset initialized!
length  1000000
states  torch.Size([1000, 1000, 17])
tensor([221.7466])


In [25]:
data.__getitem__(500015)

(tensor([ 1.1508, -0.2229, -1.6399,  1.6692,  0.7671,  0.5697, -1.6333, -0.3612,
          0.8593, -0.5344, -0.6183, -1.4405, -0.1712, -1.2628,  1.9101,  0.9054,
          0.6573]),
 tensor([ 0.5223,  1.6358, -0.4896,  1.3355,  0.4000,  0.5409]),
 tensor([1.1004]),
 tensor(0.))